- hosts: cakephp3-servers

  roles:
    - system
    - php
    - pg
    - apache
    - cakephp

  post_tasks:
    - name: 完了
      debug:
        msg: |+
          'インストールが完了しました。 http://{{ ansible_default_ipv4.address }}/cakephp/ にアクセスしてください。'
